//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelector) DeepCopyInto(out *EsgTagSelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelector.
func (in *EsgTagSelector) DeepCopy() *EsgTagSelector {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgTagSelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorList) DeepCopyInto(out *EsgTagSelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EsgTagSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorList.
func (in *EsgTagSelectorList) DeepCopy() *EsgTagSelectorList {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgTagSelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorObservation) DeepCopyInto(out *EsgTagSelectorObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorObservation.
func (in *EsgTagSelectorObservation) DeepCopy() *EsgTagSelectorObservation {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorParameters) DeepCopyInto(out *EsgTagSelectorParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDn != nil {
		in, out := &in.EndpointSecurityGroupDn, &out.EndpointSecurityGroupDn
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDnRef != nil {
		in, out := &in.EndpointSecurityGroupDnRef, &out.EndpointSecurityGroupDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.EndpointSecurityGroupDnSelector != nil {
		in, out := &in.EndpointSecurityGroupDnSelector, &out.EndpointSecurityGroupDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchKey != nil {
		in, out := &in.MatchKey, &out.MatchKey
		*out = new(string)
		**out = **in
	}
	if in.MatchValue != nil {
		in, out := &in.MatchValue, &out.MatchValue
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.ValueOperator != nil {
		in, out := &in.ValueOperator, &out.ValueOperator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorParameters.
func (in *EsgTagSelectorParameters) DeepCopy() *EsgTagSelectorParameters {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorSpec) DeepCopyInto(out *EsgTagSelectorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorSpec.
func (in *EsgTagSelectorSpec) DeepCopy() *EsgTagSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorStatus) DeepCopyInto(out *EsgTagSelectorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorStatus.
func (in *EsgTagSelectorStatus) DeepCopy() *EsgTagSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorStatus)
	in.DeepCopyInto(out)
	return out
}
