//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfile) DeepCopyInto(out *ApplicationProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfile.
func (in *ApplicationProfile) DeepCopy() *ApplicationProfile {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileList) DeepCopyInto(out *ApplicationProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileList.
func (in *ApplicationProfileList) DeepCopy() *ApplicationProfileList {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileObservation) DeepCopyInto(out *ApplicationProfileObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileObservation.
func (in *ApplicationProfileObservation) DeepCopy() *ApplicationProfileObservation {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileParameters) DeepCopyInto(out *ApplicationProfileParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsApMonPol != nil {
		in, out := &in.RelationFvRsApMonPol, &out.RelationFvRsApMonPol
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileParameters.
func (in *ApplicationProfileParameters) DeepCopy() *ApplicationProfileParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileSpec) DeepCopyInto(out *ApplicationProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileSpec.
func (in *ApplicationProfileSpec) DeepCopy() *ApplicationProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileStatus) DeepCopyInto(out *ApplicationProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileStatus.
func (in *ApplicationProfileStatus) DeepCopy() *ApplicationProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Contract) DeepCopyInto(out *Contract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Contract.
func (in *Contract) DeepCopy() *Contract {
	if in == nil {
		return nil
	}
	out := new(Contract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Contract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractList) DeepCopyInto(out *ContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Contract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractList.
func (in *ContractList) DeepCopy() *ContractList {
	if in == nil {
		return nil
	}
	out := new(ContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractObservation) DeepCopyInto(out *ContractObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractObservation.
func (in *ContractObservation) DeepCopy() *ContractObservation {
	if in == nil {
		return nil
	}
	out := new(ContractObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractParameters) DeepCopyInto(out *ContractParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]FilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FilterEntryIds != nil {
		in, out := &in.FilterEntryIds, &out.FilterEntryIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FilterIds != nil {
		in, out := &in.FilterIds, &out.FilterIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.RelationVzRsGraphAtt != nil {
		in, out := &in.RelationVzRsGraphAtt, &out.RelationVzRsGraphAtt
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.TargetDscp != nil {
		in, out := &in.TargetDscp, &out.TargetDscp
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractParameters.
func (in *ContractParameters) DeepCopy() *ContractParameters {
	if in == nil {
		return nil
	}
	out := new(ContractParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSpec) DeepCopyInto(out *ContractSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSpec.
func (in *ContractSpec) DeepCopy() *ContractSpec {
	if in == nil {
		return nil
	}
	out := new(ContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractStatus) DeepCopyInto(out *ContractStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractStatus.
func (in *ContractStatus) DeepCopy() *ContractStatus {
	if in == nil {
		return nil
	}
	out := new(ContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSubject) DeepCopyInto(out *ContractSubject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSubject.
func (in *ContractSubject) DeepCopy() *ContractSubject {
	if in == nil {
		return nil
	}
	out := new(ContractSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContractSubject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSubjectList) DeepCopyInto(out *ContractSubjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContractSubject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSubjectList.
func (in *ContractSubjectList) DeepCopy() *ContractSubjectList {
	if in == nil {
		return nil
	}
	out := new(ContractSubjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContractSubjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSubjectObservation) DeepCopyInto(out *ContractSubjectObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSubjectObservation.
func (in *ContractSubjectObservation) DeepCopy() *ContractSubjectObservation {
	if in == nil {
		return nil
	}
	out := new(ContractSubjectObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSubjectParameters) DeepCopyInto(out *ContractSubjectParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ConsMatchT != nil {
		in, out := &in.ConsMatchT, &out.ConsMatchT
		*out = new(string)
		**out = **in
	}
	if in.ContractDn != nil {
		in, out := &in.ContractDn, &out.ContractDn
		*out = new(string)
		**out = **in
	}
	if in.ContractDnRef != nil {
		in, out := &in.ContractDnRef, &out.ContractDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ContractDnSelector != nil {
		in, out := &in.ContractDnSelector, &out.ContractDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.ProvMatchT != nil {
		in, out := &in.ProvMatchT, &out.ProvMatchT
		*out = new(string)
		**out = **in
	}
	if in.RelationVzRsSdwanPol != nil {
		in, out := &in.RelationVzRsSdwanPol, &out.RelationVzRsSdwanPol
		*out = new(string)
		**out = **in
	}
	if in.RelationVzRsSubjFiltAtt != nil {
		in, out := &in.RelationVzRsSubjFiltAtt, &out.RelationVzRsSubjFiltAtt
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationVzRsSubjFiltAttRefs != nil {
		in, out := &in.RelationVzRsSubjFiltAttRefs, &out.RelationVzRsSubjFiltAttRefs
		*out = make([]v1.Reference, len(*in))
		copy(*out, *in)
	}
	if in.RelationVzRsSubjFiltAttSelector != nil {
		in, out := &in.RelationVzRsSubjFiltAttSelector, &out.RelationVzRsSubjFiltAttSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RelationVzRsSubjGraphAtt != nil {
		in, out := &in.RelationVzRsSubjGraphAtt, &out.RelationVzRsSubjGraphAtt
		*out = new(string)
		**out = **in
	}
	if in.RevFltPorts != nil {
		in, out := &in.RevFltPorts, &out.RevFltPorts
		*out = new(string)
		**out = **in
	}
	if in.TargetDscp != nil {
		in, out := &in.TargetDscp, &out.TargetDscp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSubjectParameters.
func (in *ContractSubjectParameters) DeepCopy() *ContractSubjectParameters {
	if in == nil {
		return nil
	}
	out := new(ContractSubjectParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSubjectSpec) DeepCopyInto(out *ContractSubjectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSubjectSpec.
func (in *ContractSubjectSpec) DeepCopy() *ContractSubjectSpec {
	if in == nil {
		return nil
	}
	out := new(ContractSubjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractSubjectStatus) DeepCopyInto(out *ContractSubjectStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractSubjectStatus.
func (in *ContractSubjectStatus) DeepCopy() *ContractSubjectStatus {
	if in == nil {
		return nil
	}
	out := new(ContractSubjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Epg) DeepCopyInto(out *Epg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Epg.
func (in *Epg) DeepCopy() *Epg {
	if in == nil {
		return nil
	}
	out := new(Epg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Epg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgList) DeepCopyInto(out *EpgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Epg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgList.
func (in *EpgList) DeepCopy() *EpgList {
	if in == nil {
		return nil
	}
	out := new(EpgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EpgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgObservation) DeepCopyInto(out *EpgObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgObservation.
func (in *EpgObservation) DeepCopy() *EpgObservation {
	if in == nil {
		return nil
	}
	out := new(EpgObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgParameters) DeepCopyInto(out *EpgParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDn != nil {
		in, out := &in.ApplicationProfileDn, &out.ApplicationProfileDn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDnRef != nil {
		in, out := &in.ApplicationProfileDnRef, &out.ApplicationProfileDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ApplicationProfileDnSelector != nil {
		in, out := &in.ApplicationProfileDnSelector, &out.ApplicationProfileDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExceptionTag != nil {
		in, out := &in.ExceptionTag, &out.ExceptionTag
		*out = new(string)
		**out = **in
	}
	if in.FloodOnEncap != nil {
		in, out := &in.FloodOnEncap, &out.FloodOnEncap
		*out = new(string)
		**out = **in
	}
	if in.FwdCtrl != nil {
		in, out := &in.FwdCtrl, &out.FwdCtrl
		*out = new(string)
		**out = **in
	}
	if in.HasMcastSource != nil {
		in, out := &in.HasMcastSource, &out.HasMcastSource
		*out = new(string)
		**out = **in
	}
	if in.IsAttrBasedEpg != nil {
		in, out := &in.IsAttrBasedEpg, &out.IsAttrBasedEpg
		*out = new(string)
		**out = **in
	}
	if in.MatchT != nil {
		in, out := &in.MatchT, &out.MatchT
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.PcEnfPref != nil {
		in, out := &in.PcEnfPref, &out.PcEnfPref
		*out = new(string)
		**out = **in
	}
	if in.PrefGrMemb != nil {
		in, out := &in.PrefGrMemb, &out.PrefGrMemb
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsAepgMonPol != nil {
		in, out := &in.RelationFvRsAepgMonPol, &out.RelationFvRsAepgMonPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBd != nil {
		in, out := &in.RelationFvRsBd, &out.RelationFvRsBd
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCons != nil {
		in, out := &in.RelationFvRsCons, &out.RelationFvRsCons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsConsIf != nil {
		in, out := &in.RelationFvRsConsIf, &out.RelationFvRsConsIf
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsCustQosPol != nil {
		in, out := &in.RelationFvRsCustQosPol, &out.RelationFvRsCustQosPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsDppPol != nil {
		in, out := &in.RelationFvRsDppPol, &out.RelationFvRsDppPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsFcPathAtt != nil {
		in, out := &in.RelationFvRsFcPathAtt, &out.RelationFvRsFcPathAtt
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsIntraEpg != nil {
		in, out := &in.RelationFvRsIntraEpg, &out.RelationFvRsIntraEpg
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsNodeAtt != nil {
		in, out := &in.RelationFvRsNodeAtt, &out.RelationFvRsNodeAtt
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsPathAtt != nil {
		in, out := &in.RelationFvRsPathAtt, &out.RelationFvRsPathAtt
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProtBy != nil {
		in, out := &in.RelationFvRsProtBy, &out.RelationFvRsProtBy
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProv != nil {
		in, out := &in.RelationFvRsProv, &out.RelationFvRsProv
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProvDef != nil {
		in, out := &in.RelationFvRsProvDef, &out.RelationFvRsProvDef
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsSecInherited != nil {
		in, out := &in.RelationFvRsSecInherited, &out.RelationFvRsSecInherited
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsTrustCtrl != nil {
		in, out := &in.RelationFvRsTrustCtrl, &out.RelationFvRsTrustCtrl
		*out = new(string)
		**out = **in
	}
	if in.Shutdown != nil {
		in, out := &in.Shutdown, &out.Shutdown
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgParameters.
func (in *EpgParameters) DeepCopy() *EpgParameters {
	if in == nil {
		return nil
	}
	out := new(EpgParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgSpec) DeepCopyInto(out *EpgSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgSpec.
func (in *EpgSpec) DeepCopy() *EpgSpec {
	if in == nil {
		return nil
	}
	out := new(EpgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgStatus) DeepCopyInto(out *EpgStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgStatus.
func (in *EpgStatus) DeepCopy() *EpgStatus {
	if in == nil {
		return nil
	}
	out := new(EpgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Esg) DeepCopyInto(out *Esg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Esg.
func (in *Esg) DeepCopy() *Esg {
	if in == nil {
		return nil
	}
	out := new(Esg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Esg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelector) DeepCopyInto(out *EsgEpgSelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelector.
func (in *EsgEpgSelector) DeepCopy() *EsgEpgSelector {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgEpgSelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorList) DeepCopyInto(out *EsgEpgSelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EsgEpgSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorList.
func (in *EsgEpgSelectorList) DeepCopy() *EsgEpgSelectorList {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgEpgSelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorObservation) DeepCopyInto(out *EsgEpgSelectorObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorObservation.
func (in *EsgEpgSelectorObservation) DeepCopy() *EsgEpgSelectorObservation {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorParameters) DeepCopyInto(out *EsgEpgSelectorParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDn != nil {
		in, out := &in.EndpointSecurityGroupDn, &out.EndpointSecurityGroupDn
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDnRef != nil {
		in, out := &in.EndpointSecurityGroupDnRef, &out.EndpointSecurityGroupDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.EndpointSecurityGroupDnSelector != nil {
		in, out := &in.EndpointSecurityGroupDnSelector, &out.EndpointSecurityGroupDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchEpgDn != nil {
		in, out := &in.MatchEpgDn, &out.MatchEpgDn
		*out = new(string)
		**out = **in
	}
	if in.MatchEpgDnRef != nil {
		in, out := &in.MatchEpgDnRef, &out.MatchEpgDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.MatchEpgDnSelector != nil {
		in, out := &in.MatchEpgDnSelector, &out.MatchEpgDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorParameters.
func (in *EsgEpgSelectorParameters) DeepCopy() *EsgEpgSelectorParameters {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorSpec) DeepCopyInto(out *EsgEpgSelectorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorSpec.
func (in *EsgEpgSelectorSpec) DeepCopy() *EsgEpgSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorStatus) DeepCopyInto(out *EsgEpgSelectorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorStatus.
func (in *EsgEpgSelectorStatus) DeepCopy() *EsgEpgSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgList) DeepCopyInto(out *EsgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Esg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgList.
func (in *EsgList) DeepCopy() *EsgList {
	if in == nil {
		return nil
	}
	out := new(EsgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgObservation) DeepCopyInto(out *EsgObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgObservation.
func (in *EsgObservation) DeepCopy() *EsgObservation {
	if in == nil {
		return nil
	}
	out := new(EsgObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgParameters) DeepCopyInto(out *EsgParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDn != nil {
		in, out := &in.ApplicationProfileDn, &out.ApplicationProfileDn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDnRef != nil {
		in, out := &in.ApplicationProfileDnRef, &out.ApplicationProfileDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ApplicationProfileDnSelector != nil {
		in, out := &in.ApplicationProfileDnSelector, &out.ApplicationProfileDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MatchT != nil {
		in, out := &in.MatchT, &out.MatchT
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.PcEnfPref != nil {
		in, out := &in.PcEnfPref, &out.PcEnfPref
		*out = new(string)
		**out = **in
	}
	if in.PrefGrMemb != nil {
		in, out := &in.PrefGrMemb, &out.PrefGrMemb
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCons != nil {
		in, out := &in.RelationFvRsCons, &out.RelationFvRsCons
		*out = make([]RelationFvRsConsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsConsIf != nil {
		in, out := &in.RelationFvRsConsIf, &out.RelationFvRsConsIf
		*out = make([]RelationFvRsConsIfParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsCustQosPol != nil {
		in, out := &in.RelationFvRsCustQosPol, &out.RelationFvRsCustQosPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsIntraEpg != nil {
		in, out := &in.RelationFvRsIntraEpg, &out.RelationFvRsIntraEpg
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProtBy != nil {
		in, out := &in.RelationFvRsProtBy, &out.RelationFvRsProtBy
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProv != nil {
		in, out := &in.RelationFvRsProv, &out.RelationFvRsProv
		*out = make([]RelationFvRsProvParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsScope != nil {
		in, out := &in.RelationFvRsScope, &out.RelationFvRsScope
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsScopeRef != nil {
		in, out := &in.RelationFvRsScopeRef, &out.RelationFvRsScopeRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.RelationFvRsScopeSelector != nil {
		in, out := &in.RelationFvRsScopeSelector, &out.RelationFvRsScopeSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RelationFvRsSecInherited != nil {
		in, out := &in.RelationFvRsSecInherited, &out.RelationFvRsSecInherited
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgParameters.
func (in *EsgParameters) DeepCopy() *EsgParameters {
	if in == nil {
		return nil
	}
	out := new(EsgParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelector) DeepCopyInto(out *EsgSelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelector.
func (in *EsgSelector) DeepCopy() *EsgSelector {
	if in == nil {
		return nil
	}
	out := new(EsgSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgSelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorList) DeepCopyInto(out *EsgSelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EsgSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorList.
func (in *EsgSelectorList) DeepCopy() *EsgSelectorList {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgSelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorObservation) DeepCopyInto(out *EsgSelectorObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorObservation.
func (in *EsgSelectorObservation) DeepCopy() *EsgSelectorObservation {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorParameters) DeepCopyInto(out *EsgSelectorParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDn != nil {
		in, out := &in.EndpointSecurityGroupDn, &out.EndpointSecurityGroupDn
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDnRef != nil {
		in, out := &in.EndpointSecurityGroupDnRef, &out.EndpointSecurityGroupDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.EndpointSecurityGroupDnSelector != nil {
		in, out := &in.EndpointSecurityGroupDnSelector, &out.EndpointSecurityGroupDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchExpression != nil {
		in, out := &in.MatchExpression, &out.MatchExpression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorParameters.
func (in *EsgSelectorParameters) DeepCopy() *EsgSelectorParameters {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorSpec) DeepCopyInto(out *EsgSelectorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorSpec.
func (in *EsgSelectorSpec) DeepCopy() *EsgSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorStatus) DeepCopyInto(out *EsgSelectorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorStatus.
func (in *EsgSelectorStatus) DeepCopy() *EsgSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSpec) DeepCopyInto(out *EsgSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSpec.
func (in *EsgSpec) DeepCopy() *EsgSpec {
	if in == nil {
		return nil
	}
	out := new(EsgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgStatus) DeepCopyInto(out *EsgStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgStatus.
func (in *EsgStatus) DeepCopy() *EsgStatus {
	if in == nil {
		return nil
	}
	out := new(EsgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Filter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntry) DeepCopyInto(out *FilterEntry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntry.
func (in *FilterEntry) DeepCopy() *FilterEntry {
	if in == nil {
		return nil
	}
	out := new(FilterEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FilterEntry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntryList) DeepCopyInto(out *FilterEntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FilterEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntryList.
func (in *FilterEntryList) DeepCopy() *FilterEntryList {
	if in == nil {
		return nil
	}
	out := new(FilterEntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FilterEntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntryObservation) DeepCopyInto(out *FilterEntryObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntryObservation.
func (in *FilterEntryObservation) DeepCopy() *FilterEntryObservation {
	if in == nil {
		return nil
	}
	out := new(FilterEntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntryObservation_2) DeepCopyInto(out *FilterEntryObservation_2) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntryObservation_2.
func (in *FilterEntryObservation_2) DeepCopy() *FilterEntryObservation_2 {
	if in == nil {
		return nil
	}
	out := new(FilterEntryObservation_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntryParameters) DeepCopyInto(out *FilterEntryParameters) {
	*out = *in
	if in.ApplyToFrag != nil {
		in, out := &in.ApplyToFrag, &out.ApplyToFrag
		*out = new(string)
		**out = **in
	}
	if in.ArpOpc != nil {
		in, out := &in.ArpOpc, &out.ArpOpc
		*out = new(string)
		**out = **in
	}
	if in.DFromPort != nil {
		in, out := &in.DFromPort, &out.DFromPort
		*out = new(string)
		**out = **in
	}
	if in.DToPort != nil {
		in, out := &in.DToPort, &out.DToPort
		*out = new(string)
		**out = **in
	}
	if in.EntryAnnotation != nil {
		in, out := &in.EntryAnnotation, &out.EntryAnnotation
		*out = new(string)
		**out = **in
	}
	if in.EntryDescription != nil {
		in, out := &in.EntryDescription, &out.EntryDescription
		*out = new(string)
		**out = **in
	}
	if in.EntryNameAlias != nil {
		in, out := &in.EntryNameAlias, &out.EntryNameAlias
		*out = new(string)
		**out = **in
	}
	if in.EtherT != nil {
		in, out := &in.EtherT, &out.EtherT
		*out = new(string)
		**out = **in
	}
	if in.FilterEntryName != nil {
		in, out := &in.FilterEntryName, &out.FilterEntryName
		*out = new(string)
		**out = **in
	}
	if in.Icmpv4T != nil {
		in, out := &in.Icmpv4T, &out.Icmpv4T
		*out = new(string)
		**out = **in
	}
	if in.Icmpv6T != nil {
		in, out := &in.Icmpv6T, &out.Icmpv6T
		*out = new(string)
		**out = **in
	}
	if in.MatchDscp != nil {
		in, out := &in.MatchDscp, &out.MatchDscp
		*out = new(string)
		**out = **in
	}
	if in.Prot != nil {
		in, out := &in.Prot, &out.Prot
		*out = new(string)
		**out = **in
	}
	if in.SFromPort != nil {
		in, out := &in.SFromPort, &out.SFromPort
		*out = new(string)
		**out = **in
	}
	if in.SToPort != nil {
		in, out := &in.SToPort, &out.SToPort
		*out = new(string)
		**out = **in
	}
	if in.Stateful != nil {
		in, out := &in.Stateful, &out.Stateful
		*out = new(string)
		**out = **in
	}
	if in.TCPRules != nil {
		in, out := &in.TCPRules, &out.TCPRules
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntryParameters.
func (in *FilterEntryParameters) DeepCopy() *FilterEntryParameters {
	if in == nil {
		return nil
	}
	out := new(FilterEntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntryParameters_2) DeepCopyInto(out *FilterEntryParameters_2) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ApplyToFrag != nil {
		in, out := &in.ApplyToFrag, &out.ApplyToFrag
		*out = new(string)
		**out = **in
	}
	if in.ArpOpc != nil {
		in, out := &in.ArpOpc, &out.ArpOpc
		*out = new(string)
		**out = **in
	}
	if in.DFromPort != nil {
		in, out := &in.DFromPort, &out.DFromPort
		*out = new(string)
		**out = **in
	}
	if in.DToPort != nil {
		in, out := &in.DToPort, &out.DToPort
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EtherT != nil {
		in, out := &in.EtherT, &out.EtherT
		*out = new(string)
		**out = **in
	}
	if in.FilterDn != nil {
		in, out := &in.FilterDn, &out.FilterDn
		*out = new(string)
		**out = **in
	}
	if in.FilterDnRef != nil {
		in, out := &in.FilterDnRef, &out.FilterDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.FilterDnSelector != nil {
		in, out := &in.FilterDnSelector, &out.FilterDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Icmpv4T != nil {
		in, out := &in.Icmpv4T, &out.Icmpv4T
		*out = new(string)
		**out = **in
	}
	if in.Icmpv6T != nil {
		in, out := &in.Icmpv6T, &out.Icmpv6T
		*out = new(string)
		**out = **in
	}
	if in.MatchDscp != nil {
		in, out := &in.MatchDscp, &out.MatchDscp
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.Prot != nil {
		in, out := &in.Prot, &out.Prot
		*out = new(string)
		**out = **in
	}
	if in.SFromPort != nil {
		in, out := &in.SFromPort, &out.SFromPort
		*out = new(string)
		**out = **in
	}
	if in.SToPort != nil {
		in, out := &in.SToPort, &out.SToPort
		*out = new(string)
		**out = **in
	}
	if in.Stateful != nil {
		in, out := &in.Stateful, &out.Stateful
		*out = new(string)
		**out = **in
	}
	if in.TCPRules != nil {
		in, out := &in.TCPRules, &out.TCPRules
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntryParameters_2.
func (in *FilterEntryParameters_2) DeepCopy() *FilterEntryParameters_2 {
	if in == nil {
		return nil
	}
	out := new(FilterEntryParameters_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntrySpec) DeepCopyInto(out *FilterEntrySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntrySpec.
func (in *FilterEntrySpec) DeepCopy() *FilterEntrySpec {
	if in == nil {
		return nil
	}
	out := new(FilterEntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterEntryStatus) DeepCopyInto(out *FilterEntryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterEntryStatus.
func (in *FilterEntryStatus) DeepCopy() *FilterEntryStatus {
	if in == nil {
		return nil
	}
	out := new(FilterEntryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterList) DeepCopyInto(out *FilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Filter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterList.
func (in *FilterList) DeepCopy() *FilterList {
	if in == nil {
		return nil
	}
	out := new(FilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterObservation) DeepCopyInto(out *FilterObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterObservation.
func (in *FilterObservation) DeepCopy() *FilterObservation {
	if in == nil {
		return nil
	}
	out := new(FilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterObservation_2) DeepCopyInto(out *FilterObservation_2) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterObservation_2.
func (in *FilterObservation_2) DeepCopy() *FilterObservation_2 {
	if in == nil {
		return nil
	}
	out := new(FilterObservation_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterParameters) DeepCopyInto(out *FilterParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FilterEntry != nil {
		in, out := &in.FilterEntry, &out.FilterEntry
		*out = make([]FilterEntryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FilterName != nil {
		in, out := &in.FilterName, &out.FilterName
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterParameters.
func (in *FilterParameters) DeepCopy() *FilterParameters {
	if in == nil {
		return nil
	}
	out := new(FilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterParameters_2) DeepCopyInto(out *FilterParameters_2) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.RelationVzRsFiltGraphAtt != nil {
		in, out := &in.RelationVzRsFiltGraphAtt, &out.RelationVzRsFiltGraphAtt
		*out = new(string)
		**out = **in
	}
	if in.RelationVzRsFwdRFltPAtt != nil {
		in, out := &in.RelationVzRsFwdRFltPAtt, &out.RelationVzRsFwdRFltPAtt
		*out = new(string)
		**out = **in
	}
	if in.RelationVzRsRevRFltPAtt != nil {
		in, out := &in.RelationVzRsRevRFltPAtt, &out.RelationVzRsRevRFltPAtt
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterParameters_2.
func (in *FilterParameters_2) DeepCopy() *FilterParameters_2 {
	if in == nil {
		return nil
	}
	out := new(FilterParameters_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterSpec) DeepCopyInto(out *FilterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterSpec.
func (in *FilterSpec) DeepCopy() *FilterSpec {
	if in == nil {
		return nil
	}
	out := new(FilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterStatus) DeepCopyInto(out *FilterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterStatus.
func (in *FilterStatus) DeepCopy() *FilterStatus {
	if in == nil {
		return nil
	}
	out := new(FilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportedContract) DeepCopyInto(out *ImportedContract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportedContract.
func (in *ImportedContract) DeepCopy() *ImportedContract {
	if in == nil {
		return nil
	}
	out := new(ImportedContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImportedContract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportedContractList) DeepCopyInto(out *ImportedContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImportedContract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportedContractList.
func (in *ImportedContractList) DeepCopy() *ImportedContractList {
	if in == nil {
		return nil
	}
	out := new(ImportedContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImportedContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportedContractObservation) DeepCopyInto(out *ImportedContractObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportedContractObservation.
func (in *ImportedContractObservation) DeepCopy() *ImportedContractObservation {
	if in == nil {
		return nil
	}
	out := new(ImportedContractObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportedContractParameters) DeepCopyInto(out *ImportedContractParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.RelationVzRsIf != nil {
		in, out := &in.RelationVzRsIf, &out.RelationVzRsIf
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportedContractParameters.
func (in *ImportedContractParameters) DeepCopy() *ImportedContractParameters {
	if in == nil {
		return nil
	}
	out := new(ImportedContractParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportedContractSpec) DeepCopyInto(out *ImportedContractSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportedContractSpec.
func (in *ImportedContractSpec) DeepCopy() *ImportedContractSpec {
	if in == nil {
		return nil
	}
	out := new(ImportedContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportedContractStatus) DeepCopyInto(out *ImportedContractStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportedContractStatus.
func (in *ImportedContractStatus) DeepCopy() *ImportedContractStatus {
	if in == nil {
		return nil
	}
	out := new(ImportedContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsIfObservation) DeepCopyInto(out *RelationFvRsConsIfObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsIfObservation.
func (in *RelationFvRsConsIfObservation) DeepCopy() *RelationFvRsConsIfObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsIfObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsIfParameters) DeepCopyInto(out *RelationFvRsConsIfParameters) {
	*out = *in
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.TargetDn != nil {
		in, out := &in.TargetDn, &out.TargetDn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsIfParameters.
func (in *RelationFvRsConsIfParameters) DeepCopy() *RelationFvRsConsIfParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsIfParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsObservation) DeepCopyInto(out *RelationFvRsConsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsObservation.
func (in *RelationFvRsConsObservation) DeepCopy() *RelationFvRsConsObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsParameters) DeepCopyInto(out *RelationFvRsConsParameters) {
	*out = *in
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.TargetDn != nil {
		in, out := &in.TargetDn, &out.TargetDn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsParameters.
func (in *RelationFvRsConsParameters) DeepCopy() *RelationFvRsConsParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsProvObservation) DeepCopyInto(out *RelationFvRsProvObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsProvObservation.
func (in *RelationFvRsProvObservation) DeepCopy() *RelationFvRsProvObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsProvObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsProvParameters) DeepCopyInto(out *RelationFvRsProvParameters) {
	*out = *in
	if in.MatchT != nil {
		in, out := &in.MatchT, &out.MatchT
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.TargetDn != nil {
		in, out := &in.TargetDn, &out.TargetDn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsProvParameters.
func (in *RelationFvRsProvParameters) DeepCopy() *RelationFvRsProvParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsProvParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabooContract) DeepCopyInto(out *TabooContract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabooContract.
func (in *TabooContract) DeepCopy() *TabooContract {
	if in == nil {
		return nil
	}
	out := new(TabooContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TabooContract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabooContractList) DeepCopyInto(out *TabooContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TabooContract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabooContractList.
func (in *TabooContractList) DeepCopy() *TabooContractList {
	if in == nil {
		return nil
	}
	out := new(TabooContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TabooContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabooContractObservation) DeepCopyInto(out *TabooContractObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabooContractObservation.
func (in *TabooContractObservation) DeepCopy() *TabooContractObservation {
	if in == nil {
		return nil
	}
	out := new(TabooContractObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabooContractParameters) DeepCopyInto(out *TabooContractParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabooContractParameters.
func (in *TabooContractParameters) DeepCopy() *TabooContractParameters {
	if in == nil {
		return nil
	}
	out := new(TabooContractParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabooContractSpec) DeepCopyInto(out *TabooContractSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabooContractSpec.
func (in *TabooContractSpec) DeepCopy() *TabooContractSpec {
	if in == nil {
		return nil
	}
	out := new(TabooContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabooContractStatus) DeepCopyInto(out *TabooContractStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabooContractStatus.
func (in *TabooContractStatus) DeepCopy() *TabooContractStatus {
	if in == nil {
		return nil
	}
	out := new(TabooContractStatus)
	in.DeepCopyInto(out)
	return out
}
