apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: conmurphy-provider-jet-aci
spec:
  controller:
    image: conmurphy/provider-jet-aci-controller:v0.0.10
    permissionRequests:
    - apiGroups:
      - apiextensions.crossplane.io
      resources:
      - compositions
      verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
